require:
  - 'rubocop-rails'
  - 'rubocop-rspec'

# https://docs.rubocop.org/rubocop/configuration.html
AllCops:
  Include:
    - '**/Gemfile'
    - '**/Guardfile'
    - 'app/**/*.rb'
    - 'db/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - '**/config.ru'
    - 'bin/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'Guardfile'
  NewCops: 'enable'
  RubyInterpreters:
    - 'ruby'
  TargetRailsVersion: 6.0
  TargetRubyVersion: 2.7
  StyleGuideBaseURL: 'https://rubystyle.guide'

# Globally configured Cops
# https://docs.rubocop.org/rubocop/cops.html

Bundler/OrderedGems:
  ConsiderPunctuation: true
Style/Documentation:
  Enabled: false

# # Rails Cops
# # https://docs.rubocop.org/rubocop-rails
# Rails:
#   Enabled: true
#   StyleGuideBaseURL: 'https://rails.rubystyle.guide'

# RSpec Cops
# https://docs.rubocop.org/rubocop-rspec/

RSpec:
  StyleGuideBaseURL: 'https://rspec.rubystyle.guide'
RSpec/NestedGroups:
  Max: 5
RSpec/ExampleLength:
  Enabled: false
